//! Public policy and instance identifiers. Weights never expand into virtual parties.
use num_bigint::BigUint;
use num_traits::Zero;
use serde::{Deserialize, Serialize};

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum Error {
    #[error("invalid parameters: {0}")]
    Parameters(&'static str),
    #[error("resource budget exceeded: {0}")]
    ResourceLimit(&'static str),
    #[error("invalid or noncanonical encoding")]
    Encoding,
    #[error("insufficient authenticated shares (pending, not bottom)")]
    InsufficientShares,
    #[error("invalid commitment (bottom)")]
    InvalidCommitment,
    #[error("operating system randomness failed")]
    Randomness,
}
pub type Result<T> = std::result::Result<T, Error>;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Policy {
    pub weights: Vec<BigUint>,
    pub threshold: BigUint,
    pub total: BigUint,
}
impl Policy {
    pub fn new(weights: Vec<BigUint>, threshold: BigUint) -> Result<Self> {
        if weights.is_empty() || weights.iter().any(Zero::is_zero) {
            return Err(Error::Parameters("positive weights required"));
        }
        let total: BigUint = weights.iter().sum();
        if threshold.is_zero() || threshold > total {
            return Err(Error::Parameters("require 0 < T <= W"));
        }
        Ok(Self {
            weights,
            threshold,
            total,
        })
    }
    pub fn from_strings(weights: &[String], threshold: &str) -> Result<Self> {
        fn parse(s: &str) -> Result<BigUint> {
            let (s, radix) = s.strip_prefix("0x").map_or((s, 10), |s| (s, 16));
            if s.is_empty()
                || !s.bytes().all(|b| {
                    if radix == 16 {
                        b.is_ascii_hexdigit()
                    } else {
                        b.is_ascii_digit()
                    }
                })
            {
                return Err(Error::Parameters(
                    "expected unsigned decimal or hexadecimal weight",
                ));
            }
            BigUint::parse_bytes(s.as_bytes(), radix).ok_or(Error::Encoding)
        }
        Self::new(
            weights.iter().map(|w| parse(w)).collect::<Result<_>>()?,
            parse(threshold)?,
        )
    }
    pub fn n(&self) -> usize {
        self.weights.len()
    }
    pub fn weights(&self) -> &[BigUint] {
        &self.weights
    }
    pub fn threshold(&self) -> &BigUint {
        &self.threshold
    }
    pub fn total(&self) -> &BigUint {
        &self.total
    }
    pub fn validate_async(&self) -> Result<()> {
        if &self.threshold * 3u8 > self.total {
            return Err(Error::Parameters(
                "wiAwVSS requires 3T <= W and actual corrupt weight B < T",
            ));
        }
        Ok(())
    }
    pub fn authorized(&self, members: impl IntoIterator<Item = usize>) -> Result<bool> {
        let mut seen = vec![false; self.n()];
        let mut weight = BigUint::zero();
        for i in members {
            if i >= self.n() {
                return Err(Error::Parameters("unknown party"));
            }
            if !seen[i] {
                weight += &self.weights[i];
                seen[i] = true;
            }
        }
        Ok(weight >= self.threshold)
    }
    pub fn encode(&self) -> Vec<u8> {
        let mut bytes = (self.n() as u64).to_le_bytes().to_vec();
        for value in self.weights.iter().chain(std::iter::once(&self.threshold)) {
            let value = value.to_bytes_be();
            bytes.extend_from_slice(&(value.len() as u64).to_le_bytes());
            bytes.extend_from_slice(&value);
        }
        bytes
    }
}

/// Fixed invocation context. It excludes any roots generated by sharing.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Instance {
    pub session: [u8; 32],
    pub epoch: u64,
    pub dealer: usize,
}
impl Instance {
    pub fn encode(&self) -> Vec<u8> {
        let mut bytes = self.session.to_vec();
        bytes.extend_from_slice(&self.epoch.to_le_bytes());
        bytes.extend_from_slice(&(self.dealer as u64).to_le_bytes());
        bytes
    }
}
